### PR TITLE
Lr employee list 19

### PR DESCRIPTION
**Pull request by laurenriddle**
ticket #19 
1. `git fetch --all`
2. `git checkout lr-employee-list-19`
3. run `python manage.py loaddata departments`
4. run `python manage.py loaddata employees`
5. run `python manage.py runserver`
6. go to http://localhost:8000/employees
7. see all 5 of the employees

### CODE REVIEW

**Review by klboyd — COMMENTED** [review]
Had to loaddata on departments before employees. Also don't forget to update the database connection to use Connection.db_path. After that everything ran smooth as kittens.

**Comment by laurenriddle** [comment]
I fixed the db connection, so it should be using the connections file now. Also, added load data command for departments to PR instructions. Please take another look at the branch. Thank you!

**Review by klboyd — APPROVED** [review]
Noice!

**Review by treysuiter — APPROVED** [review]
working as described

**Pull request merged**
